#!/usr/bin/clisp
(load "graphs")
(defvar *group*)
(defvar *graph*)
(defvar *base*)
(defvar *dot*)
(defvar *gif*)
(defvar *jpeg*)
(defvar *png*)
(defvar *svg*)
(run-shell-command "mkdir gif jpeg png svg")
(dotimes (count 51)
  (progn
    (setf *group* (groups:multiplicative-group (+ count 2)))
    (setf *graph* (graphs:group-orders-graph *group*))
    (setf *base* (write-to-string (+ count 2)))
    (setf *dot* (concatenate 'string *base* ".gv"))
    (setf *gif* (concatenate 'string "gif/" *base* ".gif"))
    (setf *jpeg* (concatenate 'string "jpeg/" *base* ".jpeg"))
    (setf *png* (concatenate 'string "png/" *base* ".png"))
    (setf *svg* (concatenate 'string "svg/" *base* ".svg"))
    (graphs:write-dot-file-group *graph* *dot*)
    (run-shell-command (concatenate 'string "dot -Tgif " *dot* " > " *gif*))
    (run-shell-command (concatenate 'string "dot -Tjpeg " *dot* " > " *jpeg*))
    (run-shell-command (concatenate 'string "dot -Tpng " *dot* " > " *png*))
    (run-shell-command (concatenate 'string "dot -Tsvg " *dot* " > " *svg*))
    (run-shell-command (concatenate 'string "rm " *dot*))))
